COMMENT ON COLUMN DVH_FAM_bb.FAM_BB_INNTEKTS_LISTE_ORD.TYPE_INNTEKT IS '#NAVN TYPE_INNTEKT #INNHOLD Inntekts typer hos mottaker/pliktig';
COMMENT ON COLUMN DVH_FAM_bb.FAM_BB_INNTEKTS_LISTE_ORD.PK_BB_INNTEKT IS '#NAVN PK_BB_INNTEKT #INNHOLD Primærnøkkel er en unik ID for hver rad, den er autogenerert';
COMMENT ON COLUMN DVH_FAM_bb.FAM_BB_INNTEKTS_LISTE_ORD.LASTET_DATO IS '#NAVN LASTET_DATO #INNHOLD Tidsstempel som angir når en rad ble lagt til i tabellen';
COMMENT ON COLUMN DVH_FAM_bb.FAM_BB_INNTEKTS_LISTE_ORD.BELOP IS '#NAVN BELOP #INNHOLD Inntekt for den aktuelle arbeids type';
COMMENT ON COLUMN DVH_FAM_bb.FAM_BB_INNTEKTS_LISTE_ORD.KAFKA_OFFSET IS '#NAVN KAFKA_OFFSET #INNHOLD ';
COMMENT ON COLUMN DVH_FAM_bb.FAM_BB_INNTEKTS_LISTE_ORD.FK_BB_BIDRAGS_PERIODE IS '#NAVN FK_BB_BIDRAGS_PERIODE #INNHOLD Fremmednøkkel til fam_bb_bidrags_periode tabellen';
COMMENT ON COLUMN DVH_FAM_bb.FAM_BB_INNTEKTS_LISTE_ORD.FLAGG IS '#NAVN FLAGG #INNHOLD M/P flagg som angir om inntekten hører til mottakeren eller til pliktig';
