COMMENT ON COLUMN DVH_FAM_bb.FAM_BB_INNTEKT.TYPE_INNTEKT IS '#NAVN TYPE_INNTEKT #INNHOLD Inntekts typer hos mottaker';
COMMENT ON COLUMN DVH_FAM_bb.FAM_BB_INNTEKT.PK_BB_INNTEKT IS '#NAVN PK_BB_INNTEKT #INNHOLD Primærnøkkel er en unik ID for hver rad, den er autogenerert';
COMMENT ON COLUMN DVH_FAM_bb.FAM_BB_INNTEKT.LASTET_DATO IS '#NAVN LASTET_DATO #INNHOLD Tidsstempel som angir når en rad ble lagt til i tabellen';
COMMENT ON COLUMN DVH_FAM_bb.FAM_BB_INNTEKT.BELOP IS '#NAVN BELOP #INNHOLD Inntekt for den aktuelle arbeids type';
COMMENT ON COLUMN DVH_FAM_bb.FAM_BB_INNTEKT.KAFKA_OFFSET IS '#NAVN KAFKA_OFFSET #INNHOLD ';
COMMENT ON COLUMN DVH_FAM_bb.FAM_BB_INNTEKT.FK_BB_FORSKUDDS_PERIODE IS '#NAVN FK_BB_FORSKUDDS_PERIODE #INNHOLD Fremmednøkkel til fam_bb_forskudds_periode tabellen';
