comment on column dvh_fam_bb.fak_bb_forskudd.aar_maaned is '#NAVN StatistikkMaaned #INNHOLD Statistikk maaned (yyyymm)';
comment on column dvh_fam_bb.fak_bb_forskudd.fk_person1_kravhaver is '#NAVN FK_PERSON1TilKravhaver #INNHOLD Fk_person1 til barn (kravhaver) = mapping til fnr. DVH sin identifikator for FNR.';
comment on column dvh_fam_bb.fak_bb_forskudd.fk_person1_mottaker is '#NAVN FK_PERSON1TilMottaker #INNHOLD Fk_person1 til mottaker = mapping til fnr. DVH sin identifikator for FNR.';
comment on column dvh_fam_bb.fak_bb_forskudd.vedtakstidspunkt is '#NAVN Vedtakstidspunkt #INNHOLD Tidspunkt til når vedtaket ble fattet';
comment on column dvh_fam_bb.fak_bb_forskudd.fk_bb_fagsak is '#NAVN FremmednøkkelTilFagsak #INNHOLD Fremmednøkkel til rekorden i fam_bb_fagsak_ord tabellen';
comment on column dvh_fam_bb.fak_bb_forskudd.saksnr is '#NAVN Saksnummer #INNHOLD Saksnummer';
comment on column dvh_fam_bb.fak_bb_forskudd.vedtaks_id is '#NAVN VedtaksId #INNHOLD Versjon av aktuell saksnummer';
comment on column dvh_fam_bb.fak_bb_forskudd.behandlings_type is '#NAVN BehandlingsType #INNHOLD Grunnlag for å behandle saken';
comment on column dvh_fam_bb.fak_bb_forskudd.fk_bb_forskudds_periode is '#NAVN FremmednøkkelTilPeriode #INNHOLD Fremmednøkkel til rekorden i FAK_BB_forskudds_periode_ord';
comment on column dvh_fam_bb.fak_bb_forskudd.periode_fra is '#NAVN PeriodeFra #INNHOLD Perioden vedtaket er gyeldig fra';
comment on column dvh_fam_bb.fak_bb_forskudd.periode_til is '#NAVN PeriodeTil #INNHOLD Perioden vedtaket er gyeldig til(hvis den er null, betyr det at vedtaket er fortsatt gyldig)';
comment on column dvh_fam_bb.fak_bb_forskudd.belop is '#NAVN Belop #INNHOLD Sum beløp som er betalt for mottaker for gjeldende kravhaver';
comment on column dvh_fam_bb.fak_bb_forskudd.resultat is '#NAVN Resultat #INNHOLD Resultat av vurdering av saksen for en bestemt periode';
comment on column dvh_fam_bb.fak_bb_forskudd.barnets_alders_gruppe is '#NAVN BARNETS_ALDERS_GRUPPE #INNHOLD Alders_gruppe til kravhaver, alders gruppe er delt til 2 grupper ALDER_0_10_ÅR og ALDER_11_17_ÅR';
comment on column dvh_fam_bb.fak_bb_forskudd.periode_fra_opphor is '#NAVN PERIODE_FRA_OPPHOR #INNHOLD Perioden fra når vedtaket ble opphørt (denne kan være null)';
comment on column dvh_fam_bb.fak_bb_forskudd.aar is '#NAVN AAR #INNHOLD Statistikkår';
comment on column dvh_fam_bb.fak_bb_forskudd.max_vedtaksdato is '#NAVN MAX_VEDTAKSDATO #INNHOLD Max dato for vedtak somblir prosessert per perioden';
comment on column dvh_fam_bb.fak_bb_forskudd.fk_dim_tid_mnd is '#NAVN FK_DIM_TID_MND #INNHOLD Fremmednøkkel til dim tid';
comment on column dvh_fam_bb.fak_bb_forskudd.periode_type is '#NAVN PERIODE_TYPE #INNHOLD Den kan være alt fra m (maaned), y (aar), k (kvartal) osv';
comment on column dvh_fam_bb.fak_bb_forskudd.fk_dim_person_kravhaver is '#NAVN FK_DIM_PERSON_KRAVHAVER #INNHOLD Fk_dim_person til barn (fremmednøkkel i dim person tabell)';
comment on column dvh_fam_bb.fak_bb_forskudd.alder_kravhaver is '#NAVN ALDER_KRAVHAVER #INNHOLD Barnets alder';
comment on column dvh_fam_bb.fak_bb_forskudd.kjonn_kravhaver is '#NAVN KJONN_KRAVHAVER #INNHOLD Barnets kjønn';
comment on column dvh_fam_bb.fak_bb_forskudd.fk_dim_person_mottaker is '#NAVN FK_DIM_PERSON_MOTTAKER #INNHOLD Fk_dim_person til mottaker';
comment on column dvh_fam_bb.fak_bb_forskudd.bosted_kommune_nr_mottaker is '#NAVN BOSTED_KOMMUNE_NR_MOTTAKER #INNHOLD Kommune nummer til kommunen mottaker bor i';
comment on column dvh_fam_bb.fak_bb_forskudd.fk_dim_land_statsborgerskap_mottaker is '#NAVN FK_DIM_LAND_STATSBORGERSKAP_MOTTAKER #INNHOLD Fremmednøkkel til landet mottaker er statsborger i';
comment on column dvh_fam_bb.fak_bb_forskudd.fk_dim_geografi_bosted_mottaker is '#NAVN FK_DIM_GEOGRAFI_BOSTED_MOTTAKER #INNHOLD Fremmednøkkel til det geografiske omraadet mottaker bor i';
comment on column dvh_fam_bb.fak_bb_forskudd.alder_mottaker is '#NAVN ALDER_MOTTAKER #INNHOLD Mottakerens alder';
comment on column dvh_fam_bb.fak_bb_forskudd.inntekt_total is '#NAVN INNTEKT_TOTAL #INNHOLD Sum av alle belop hos mottaker';
comment on column dvh_fam_bb.fak_bb_forskudd.antall_inntekts_typer is '#NAVN ANTALL_INTTEKTS_TYPER #INNHOLD Antall type inntekt hos mottaker';
comment on column dvh_fam_bb.fak_bb_forskudd.gyldig_flagg is '#NAVN GYLDIG_FLAGG #INNHOLD Et flagg som vi setter til aa merke en kjøring';
comment on column dvh_fam_bb.fak_bb_forskudd.lastet_dato is '#NAVN LASTET_DATO #INNHOLD Dato naar datat ble lastet opp til tabellen';
comment on column dvh_fam_bb.fak_bb_forskudd.inntekt_1 is '#NAVN INNTEKT_1 #INNHOLD Belop paa inntekt 1 hos mottaker  (hvis finnes)';
comment on column dvh_fam_bb.fak_bb_forskudd.inntekt_2 is '#NAVN INNTEKT_2 #INNHOLD Belop paa inntekt 2 hos mottaker  (hvis finnes)';
comment on column dvh_fam_bb.fak_bb_forskudd.inntekt_3 is '#NAVN INNTEKT_3 #INNHOLD BELOP Paa inntekt 3 hos mottaker  (hvis finnes)';
comment on column dvh_fam_bb.fak_bb_forskudd.inntekt_4 is '#NAVN INNTEKT_4 #INNHOLD BELOP PAa Inntekt 4 Hos Mottaker  (Hvis Finnes)';
comment on column dvh_fam_bb.fak_bb_forskudd.type_inntekt_1 is '#NAVN TYPE_INNTEKT_1 #INNHOLD Inntekts type 1 hos mottaker';
comment on column dvh_fam_bb.fak_bb_forskudd.type_inntekt_2 is '#NAVN TYPE_INNTEKT_2 #INNHOLD Inntekts type 2 hos mottaker';
comment on column dvh_fam_bb.fak_bb_forskudd.type_inntekt_3 is '#NAVN TYPE_INNTEKT_3 #INNHOLD Inntekts type 3 hos mottaker';
comment on column dvh_fam_bb.fak_bb_forskudd.type_inntekt_4 is '#NAVN TYPE_INNTEKT_4 #INNHOLD Inntekts type 4 hos mottaker';
comment on column dvh_fam_bb.fak_bb_forskudd.forste_vedtakstidspunkt is '#NAVN ForsteVedtakstidspunkt #INNHOLD Første dato for saksnr knyttet til kravhaver';
comment on column dvh_fam_bb.fak_bb_forskudd.antall_barn_i_egen_husstand is '#NAVN AntallBarnIEgenHusstand #INNHOLD Antall barn i egen husstand';
comment on column dvh_fam_bb.fak_bb_forskudd.sivilstand is '#NAVN Sivilstand #INNHOLD Sivilstand til mottaker';
comment on column dvh_fam_bb.fak_bb_forskudd.barn_bor_med_bm is '#NAVN BarnBorMedBM #INNHOLD Flagg på om barn bor sammen med bidragsmottaker';