version: 2

sources:
  - name: admin
    schema: sys
    tables:
      - name: dba_role_privs
      - name: dba_tab_privs
      - name: dba_sys_privs

  - name: admin_dmo
    schema: dvh_dmo
    tables: 
       - name: dmo_ops_users
       - name: dmo_dstr_objects_to_team

  - name: person
    schema: dt_person
    tables:
      - name: dim_person
        description: 'inneholder informasjon om brukere, bla kjonn, fodeland, statsborgerskap osv'
      - name: ident_off_id_til_fk_person1
      - name: ident_off_id_til_fk_person1_ikke_skjermet

  - name: kode_verk
    schema: dt_kodeverk
    tables:
      - name: dim_alder
        descrition: 'Dimensjonsverdier for alder.'
      - name: dim_tid
      - name: dim_geografi
      - name: dim_kjonn

  - name: fam_bb
    schema: dvh_fam_bb
    tables:
      - name: fam_bb_meta_data
        description: 'inneholder meta_data for barnebidrag forskudd og bidrag'
      - name: fam_bb_fagsak
        description: 'inneholder vedtaksinformasjon for forskudd biten'
      - name: fam_bb_fagsak_ord
        description: 'inneholder vedtaksinformasjon for bidrga biten'
      - name: fam_bb_forskudds_periode
      - name: fam_bb_bidrags_periode_ord
      - name: fam_bb_inntekts_liste_ord
      - name: fam_bb_inntekt
      - name: stg_fam_bb_barn_bis
      - name: stg_fam_bb_mottaker_bis      
      - name: stg_fam_bb_pliktige_bis
      - name: stg_fam_bb_barn_berm
      - name: stg_fam_bb_mottaker_berm      
      - name: stg_fam_bb_pliktige_berm
      - name: fam_bb_bidrag_resultat_mapping



