version: 2

sources:
  - name: admin
    schema: sys
    tables:
      - name: dba_role_privs
      - name: dba_tab_privs
      - name: dba_sys_privs

  - name: admin_dmo
    schema: dvh_dmo
    tables: 
       - name: dmo_ops_users
       - name: dmo_dstr_objects_to_team

  - name: person
    schema: dt_person
    tables:
      - name: dim_person
        description: 'inneholder informasjon om brukere, bla kjonn, fodeland, statsborgerskap osv'
      - name: ident_off_id_til_fk_person1
      - name: ident_off_id_til_fk_person1_ikke_skjermet

  - name: kode_verk
    schema: dt_kodeverk
    tables:
     - name: dim_tid
     - name: dim_geografi
     - name: dim_kjonn

  - name: fam_bb
    schema: dvh_fam_bb
    tables:
      - name: fam_bb_meta_data
        description: 'inneholder meta_data for barnebidrag forskudd og bidrag'
      - name: fam_bb_fagsak
        description: 'inneholder vedtaksinformasjon for forskudd biten'
      - name: fam_bb_fagsak_ord
        description: 'inneholder vedtaksinformasjon for bidrga biten'
      - name: fam_bb_forskudds_periode
      - name: fam_bb_bidrags_periode_ord
      - name: fam_bb_inntekts_liste_ord
      - name: fam_bb_inntekt
      - name: stg_fam_bb_barn_bis
      - name: stg_fam_bb_mottaker_bis      
      - name: stg_fam_bb_pliktige_bis
      - name: stg_fam_bb_barn_berm
      - name: stg_fam_bb_mottaker_berm      
      - name: stg_fam_bb_pliktige_berm
      - name: fam_bb_bidrag_resultat_mapping



models:

  - name: fam_bb_saerbidrag_inntekt
    columns:
      - name: pk_bb_inntekt_saerbidrag  
        tests:
          - not_null
          - unique    
      - name: fk_bb_saerbidrag_fagsak
        tests:
          - not_null

          # FOREIGN KEY
          - relationships:
              to: ref('fam_bb_saerbidrag_fagsak')
              field: pk_bb_saerbidrag_fagsak 


  - name: fam_bb_saerbidrag_fagsak
    description: "Tabell for særbidragsvedtak."
    columns:
      - name: pk_bb_saerbidrag_fagsak
        description: "Unik nøkkel for tabellen."
        tests:
          - not_null
          - unique
      - name: kafka_offset
        description: "Kafka-kø sekvensnummer."
      - name: fk_bb_meta_data
        description: "Syntetisk fremmednøkkel mot kildetabellen."
      - name: vedtaks_id
        description: "Vedtakets ID."
      - name: vedtaks_tid
        description: "Vedtakets tidspunkt."
      - name: behandlings_type
        description: "Vedtakets type, for eksempel fastsettelse, endring eller klage."
      - name: kategori
        description: "Vedtakets kategori, for eksempel tannregulering."
      - name: saksnr
        description: "Saksnummeret vedtaket er en del av."
      - name: fk_person1_skyldner
        description: "Syntetisk identifikator for skyldner."
      - name: fk_person1_kravhaver
        description: "Syntetisk identifikator for kravhaver."
      - name: fk_person1_mottaker
        description: "Syntetisk identifikator for mottaker."
      - name: belop
        description: "Beløp."
      - name: valuta_kode
        description: "Valutakoden tilknyttet beløpet."
      - name: resultat
        description: "Vedtakets resultat, for eksempel innvilget eller avslag."
      - name: innkreving_flagg
        description: "Binær verdi som viser om vedtaket er registrert for innkreving via Skatt."
      - name: omgjor_vedtaks_id
        description: "Viser til hvilken vedtaks id et vedtak skal omgjøre, dersom det skjer endringer på et vedtak."
      - name: historisk_flagg
        description: "Binær verdi som viser vedtakets systemtilknytning. Hvis 1 er det snakk om eldre fagsystem."
      - name: krav_belop
        description: "Kravbeløp."
      - name: godkjent_belop
        description: "Godkjent beløp."
      - name: betalt_belop
        description: "Betalt beløp."
      - name: lastet_dato
        description: "Data lastet inn i tabellen i datavarehuset."